### ISSUE TITLE
Upgraded to Version 0.2.3-beta and integration doesn't work

### ISSUE THREAD

**Issue by Anto79-ops** [uvjustin/alarmdotcom#107]
Thanks for your awesome work here! This integration relies on quite a few automations for me so noticed almost immediately when there was a problem. Today, I noticed an update was available to version 0.2.3-beta (April 5, 2022), installed it and restarted HA and upon restart, my intergration doesn't seem to work anymore. Sorry, I didnt read the release notes this time. Are there instructions I missed?

Error migrating entry _provider:@email.com_ for alarmdotcom

This error originated from a custom integration.

```
Logger: homeassistant.config_entries
Source: custom_components/alarmdotcom/__init__.py:150
Integration: Alarm.com (documentation, issues)
First occurred: 7:02:20 PM (1 occurrences)
Last logged: 7:02:20 PM

Error migrating entry NAME and EMAIL for alarmdotcom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 553, in async_migrate
    result = await component.async_migrate_entry(hass, self)
  File "/config/custom_components/alarmdotcom/__init__.py", line 150, in async_migrate_entry
    if not v3_options["use_arm_code"]:
KeyError: 'use_arm_code'
```

**Comment by elahd** [comment]
Would you mind checking v0.2.3-beta.1?

Thanks for testing!

**Comment by Anto79-ops** [comment]
I'd be happy to. How do I actually get that version? I have it currently installed through Hacs.

**Comment by elahd** [comment]
From within HACS, use the "Update information" option for the integration to force a check for new versions:

![image](https://user-images.githubusercontent.com/466460/161994429-5240650c-c423-42e1-97cf-e972d2a1461f.png)

Once you do that, you should see a prompt to update. If you don't, select the "Redownload" option, select "Show beta versions," and wait a few seconds:

![image](https://user-images.githubusercontent.com/466460/161994724-25f06b42-c9ed-4fc4-8841-6d7c98d4176e.png)

**Comment by Anto79-ops** [comment]
thank you very much! That was simple to fix after following your instructions. All is working now.
