### ISSUE TITLE
Disable Use Delay by default

### ISSUE THREAD

**Issue by BinaryShrub** [uvjustin/alarmdotcom#110]
I recently upgraded from 2.1, and by default use delay was turned on for all three modes, which results in my alarm going off immediately when opening a delayed contact. I don't know if the logic is reversed, but it might be something you want to look into so others don't have the same problem.

Turning off `use delay` for all three of my modes resulted in expected experience of panel delay before alarming.

**Comment by elahd** [comment]
Sorry about that. This is fixed in v0.2.4, but you'll need to update your delay settings after you update. Would you mind updating and reporting back here?

**Comment by mecarroll** [comment]
Where is this setting changed?

**Comment by elahd** [comment]
![image](https://user-images.githubusercontent.com/466460/163683739-863771d5-d971-4379-8379-eee082e9b4e0.png)

![image](https://user-images.githubusercontent.com/466460/163683779-490e3542-a6f6-4d8f-93ef-fc0d6c0660a0.png)

![image](https://user-images.githubusercontent.com/466460/163683793-06b6611c-3fca-47ff-81f1-47a82dc3f81e.png)

It's the "Arming Delay" setting. When checked, the arming delay will be used.
