### ISSUE TITLE
Lock status only shows "Locked" on v0.2.3+

### ISSUE THREAD

**Issue by tholland15** [uvjustin/alarmdotcom#113]
Locking and unlocking locks works as expected. However the status of the locks are always `Locked` since upgrading to v0.2.3-v0.2.5.

**Comment by elahd** [comment]
> Locking and unlocking locks works as expected. However the status of the locks are always Locked since upgrading to v0.2.3-v0.2.5.

Would you mind testing this before I push to prod? To test:

1. From your HACS page, click on Redownload in the Alarmdotcom card's menu:
![image](https://user-images.githubusercontent.com/466460/163047616-853cc8b8-6eb0-40a8-8f9b-f1335f5f79ea.png)
2. Select "master" from the "Select version" dropdown, then click on "Download".
![image](https://user-images.githubusercontent.com/466460/163047867-daf26b0a-f5ab-436e-b76a-d1b4aeab7530.png)
3. Restart Home Assistant.

> I'm loving all the new features and capabilities added to this integration lately, but not loving all the bugs that are coming along for the ride and slipping into shipped releases 😟

Totally get this, but moving fast is the only way I stay motivated to deliver with this project. I also don't have access to enough Alarm.com devices to properly test real hardware and don't have enough experience writing Python tests to want to take on unit testing.

(Full disclosure: I live in a NYC doorman building and don't have an alarm system. I have a close family member with a Surety/Alarm.com system that I use for testing and commit code to this repo purely for entertainment.)

Anyway, it would be _awesome_ if someone could help with testing. No hard feelings if that person isn't you!

**Comment by tholland15** [comment]
Unfortunately no change after downloading master. All locks are still `Locked` after unlocking them and waiting 5 minutes. 

I edited the issue to remove my comment about the bugs right after I posted as I realized it was in bad taste and did not want to demotivate you from all your amazing contributions to this integration! It's amazing what you've been able to accomplish without even having a system of your own! I had no idea. Wow!

I'm happy to do any testing that I can, but the only "unique" devices I have in my system are the locks.

**Comment by elahd** [comment]
Alright, try this:

1. Run through the "redownloading from master" steps above, then restart Home Assistant.
2. In Home Assistant, go to Configuration > Devices & Services.
3. Click on the "[X] Devices" link in the Alarm.com card:
![image](https://user-images.githubusercontent.com/466460/163287195-853ea308-082a-466c-a0c6-67c121262b47.png)
4. Find your lock in the devices list and click on it.
5. In the lock's Diagnostics card, "PRESS" the Debug button:
![image](https://user-images.githubusercontent.com/466460/163287625-392ba83f-dfc0-400f-8c41-66246637a853.png)
6. Go to Configuration (in the left nav, not in the Alarm.com card) > Settings > Logs.
7. Click on the Alarm.com log entry for your lock:
![image](https://user-images.githubusercontent.com/466460/163287757-2ded5209-c30f-40c2-b329-c16bcfc5c429.png)
9. Copy the stuff in red and post it here:
![image](https://user-images.githubusercontent.com/466460/163287853-20540eb3-6330-49d9-af2f-90cfd941002d.png)

**Comment by elahd** [comment]
@tholland15 Did you have the chance to look at this?

**Comment by tholland15** [comment]
Sorry, I was away from home for several days over the holiday weekend. 

I just started to gather the debug info, by first upgrading to 0.2.6 and now it works! No other changes, just upgrading to 0.2.6 seems to have fixed it. 

Separately, these debug buttons are great and will make future debugging much easier. 

Closing this issue. Thanks for the fix @elahd!
