### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by IbeAbitGoofy** [uvjustin/alarmdotcom#116]
When clicking on Configuration in Integrations, receive the following:

Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by elahd** [comment]
That's a weird one. I see that specific message in the home assistant forums. Can you reply with:

1. Home Assistant version
2. Alarm.com integration version
3. More details from the logs. Do you only see that message, or is there more info attached to it?

Lastly, can you try making sure your internal/external URLs are set correctly?

https://community.home-assistant.io/t/official-smartthings-integration-error-config-flow-could-not-be-loaded-500-internal-server-error-server-got-itself-in-trouble/393292/4

**Comment by IbeAbitGoofy** [comment]
I think I've figured it out.  I appeared to still be on HA 2022.02.  Upgraded to the latest version and that fixed the issue.
