### ISSUE TITLE
Z-wave locks not available after update(s)?

### ISSUE THREAD

**Issue by Anto79-ops** [uvjustin/alarmdotcom#130]
Hey nice integration here, been working relatively smoothly for months.

Yesterday and this morning I updated both this code to 0.2.8 (and the beta before that, yesterday) and I also updated this morning to 2022.6 at around the time.

My z-wave locks (all 3) are showing up as unavailable now. Everything else seems (all other sensors) to be working as normal.
I’m not sure if this is local issue or recent update issue.

Any troubleshooting tips? thanks

**Comment by Anto79-ops** [comment]
sorry, I don't know why the "new device" label is listed on my post.

**Comment by Anto79-ops** [comment]
i should mention that the lock seems to be report the diagnostics (battery, debug, malfucntion), but not the actual state controls i.e. lock, unlocked that is unavailable.

<img width="624" alt="Untitled" src="https://user-images.githubusercontent.com/79593761/171522185-76041e3e-4d0d-47e3-b02e-2022483f9cdf.png">
.

**Comment by Lurick73** [comment]
Seeing similar issues when trying to toggle lights and whatnot via the integration as well.

```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/light/__init__.py", line 545, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/home/homeassistant/.homeassistant/custom_components/alarmdotcom/light.py", line 157, in async_turn_off
    await self.async_turn_off_callback()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyalarmdotcomajax/devices.py", line 629, in async_turn_off
    await self._send_action_callback(
  File "/srv/homeassistant/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 429, in async_send_command
    raise ConnectionError
ConnectionError
```

**Comment by elahd** [comment]
Are you both able to try this again using v0.2.9-beta?

**Comment by Lurick73** [comment]
> Are you both able to try this again using v0.2.9-beta?

Yup, loaded up 0.2.9-beta just now and I can tell that I can toggle lights BUT I noticed it shows my lock (which was previously available) as "unavailable" now.

**Comment by elahd** [comment]
Thanks for the update. I put v0.2.8 back into beta until we work this out so others aren't prompted to download.

Would you mind hitting the debug button for your lock in Home Assistant? That'll post a block of text to your Home Assistant logs. It would be helpful if you could paste that text in here, redacting the ID and device name if those are sensitive. Things have moved around recently in HA. Logs are now in Settings > System > Logs. You'll see an entry that looks like this:

![image](https://user-images.githubusercontent.com/466460/171643314-7f2098f4-8bf0-4439-98b0-21347a39418d.png)

Click the copy button:

![image](https://user-images.githubusercontent.com/466460/171644000-68b62de5-3b4f-4ade-931e-876649d74fce.png)

and paste the text as a response here. You can redact MAC addresses, names, etc. that you consider private.

As for the battery sensor, that was an artificial restriction that I lifted for this release. Basically, Alarm.com doesn't make it clear through the API which devices actually have batteries -- they all report "normal" battery levels, even if they're hardwired. For prior releases, I limited battery sensors to locks and sensors. Now, they'll show for everything but will only alert when ADC reports low or critical battery level (which will only happen for devices that actually use batteries).

**Comment by Anto79-ops** [comment]
thanks, all. Here's my debug code (if you need it)

```
This error originated from a custom integration.

Logger: custom_components.alarmdotcom
Source: custom_components/alarmdotcom/__init__.py:131
Integration: Alarm.com (documentation, issues)
First occurred: 8:05:47 AM (1 occurrences)
Last logged: 8:05:47 AM

ALARM.COM DEBUG DATA FOR BACK DOOR: {'state': 1, 'desiredState': 1, 'maxUserCodeLength': 8, 'supportsScheduledUserCodes': True, 'supportsTemporaryUserCodes': True, 'supportsLatchControl': False, 'canEnableRemoteCommands': False, 'managedDeviceType': 6, 'canBeRenamed': True, 'hasState': True, 'availableOnDemandCodes': 0, 'totalOnDemandCodes': 0, 'canBeDeleted': True, 'canAccessWebSettings': False, 'canAccessAppSettings': False, 'webSettings': 1001, 'canAccessTroubleshootingWizard': False, 'troubleshootingWizard': None, 'macAddress': '', 'manufacturer': 'Kwikset', 'isOAuth': False, 'isZWave': True, 'supportsCommandClassBasic': True, 'isMalfunctioning': False, 'canBeSaved': True, 'canChangeDescription': True, 'description': 'Back Door', 'deviceModelId': 91, 'canConfirmStateChange': True, 'canReceiveCommands': True, 'remoteCommandsEnabled': True, 'hasPermissionToChangeState': True, 'deviceIcon': {'icon': 28}, 'batteryLevelNull': 60, 'lowBattery': False, 'criticalBattery': False, 'canBeLinkedToVideoDevice': True, 'videoDeviceLinkDeviceIds': []}
```

**Comment by elahd** [comment]
Thanks. Can you try again with v0.2.9-beta.1?

**Comment by Lurick73** [comment]
> Thanks. Can you try again with v0.2.9-beta.1?

Can confirm with 0.2.9-beta.1 I can see the lock state again and control it without issue.

**Comment by Anto79-ops** [comment]
Same here. Thank you for fixing it so quickly awesome!

**Comment by elahd** [comment]
Perfect! Sorry for the trouble and thanks for the quick follow ups!
