### ISSUE TITLE
v2.9 Skybell 

### ISSUE THREAD

**Issue by jriffe6** [uvjustin/alarmdotcom#133]
I saw in the release notes that Skybell was supported for doorbells but with that version and the latest version I am not showing any new devices other than what was already pulled in my case just the garage door and door lock.  I am running the latest version of HA also.

**Comment by jriffe6** [comment]
Sorry I have the slimline version I didn't see HD my bad.

**Comment by elahd** [comment]
All good. I don't think that I'll be able to support an entirely new device right now, but if you're willing to do some light testing I can see if the Slimline can use the code I wrote for the HD. If the config pages are the same it should be an easy change. How does that sound?

**Comment by jriffe6** [comment]
I would be willing but fair warning I am in the process of migrating to HA from Hubitat so I don’t really know much but I would be willing to try. Sent from Mail for Windows From: Elahd Bar-ShaiSent: Friday, June 3, 2022 9:37 AMTo: uvjustin/alarmdotcomCc: jriffe6; State changeSubject: Re: [uvjustin/alarmdotcom] v2.9 Skybell (Issue #133) All good. I don't think that I'll be able to support an entirely new device right now, but if you're willing to do some light testing I can see if the Slimline can use the code I wrote for the HD. If the config pages are the same it should be an easy change. How does that sound?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***> Virus-free. www.avg.com
