### ISSUE TITLE
Not a big issue but wanted to let you know it's not showing up in HACS

### ISSUE THREAD

**Issue by mystex** [uvjustin/alarmdotcom#22]
I'll install manually but thing it'd be great if it showed up in HACS.

**Comment by uvjustin** [comment]
@aechelon Any idea how to do this? I don't use HACS myself...

**Comment by aechelon** [comment]
I'm using the plugin through HACS without issues.  Perhaps you need to add the repo?
There's a Custom Repositories option when you click on the three dots at the top-right corner of the HACS interface.  You can provide the URL for this plugin there and click ADD.

**Comment by mystex** [comment]
I wasn't saying it wouldn't work but more that it's not showing up in the search when you do the add repositories.

**Comment by uvjustin** [comment]
I added the repository to HACS default, and it got pulled into the master 2 days ago. Does it work now? (I still don't use HACS myself so I can't check)

**Comment by iKingRPG** [comment]
> I added the repository to HACS default, and it got pulled into the master 2 days ago. Does it work now? (I still don't use HACS myself so I can't check)

Around 2 days ago I noticed it is finally added to HACS. I successfully installed it using HACS and it is working :)

Thanks for making this.
