### ISSUE TITLE
Component name may be confusing

### ISSUE THREAD

**Issue by uvjustin** [uvjustin/alarmdotcom#23]
This component was named alarmdotcomajax to differentiate it from the original alarmdotcom component. The "ajax" suffix may be misleading given that there is actually an alarm system with the name Ajax Systems. Given that the original alarmdotcom integration no longer exists, maybe we should rename this component back to alarmdotcom. @aechelon thoughts?

**Comment by aechelon** [comment]
I agree.

**Comment by uvjustin** [comment]
Changing the component name should be easy enough, but the pypi library name pyalarmdotcom is already taken. Should we rename the pypi library to something else or just keep it as is?

**Comment by aechelon** [comment]
I'd keep it as-is...  Mostly because I don't have a clever suggestion, but that would also make it so that any older forks could still be associated by name.

**Comment by uvjustin** [comment]
Ok. I'll wait til the weekend to do it in case some people have to switch out the component/change the component name in config yaml

**Comment by aechelon** [comment]
Not sure if it's appropriate since it's not a built-in component, but maybe we should give the HA folks a heads up so they put it in their release notes?

**Comment by uvjustin** [comment]
I don't think it's in scope since it's no longer a built in integration...maybe just post a heads up on the forums?

**Comment by aechelon** [comment]
Sounds good

**Comment by uvjustin** [comment]
Renamed the component and repository.
