### ISSUE TITLE
Cannot import AlarmdotcomADT error on last build

### ISSUE THREAD

**Issue by csmarcolino** [uvjustin/alarmdotcom#24]
I don't have adt on my alarm.com so I set adt to false and got the error bellow. I delete the adt from my config and still got the error. 
I reverterted to the commit before the adt commit (sep 2 if am not mistaken) and error is gone

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:407
Integration: Hass.io (documentation, issues)
First occurred: November 19, 2020, 8:23:14 PM (5 occurrences)
Last logged: 6:30:45 PM

Platform error alarm_control_panel.alarmdotcomajax - cannot import name 'AlarmdotcomADT' from 'pyalarmdotcomajax' (/usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/__init__.py)

**Comment by uvjustin** [comment]
Your hassio is not updating the pypi library to the version in the manifest.json. I'm not sure why that is happening, but it's not a problem with the component.
@aechelon Any ideas why some people seem to have problems with pypi requirements?

**Comment by uvjustin** [comment]
This is related to https://github.com/uvjustin/alarmdotcom/issues/25
For some reason your HA does not pull the updated version of the pypi library automatically. No idea why this happens. To work around just install the pyalarmdotcomajax library using pip.

**Comment by uvjustin** [comment]
@csmarcolino Still having that problem?

**Comment by csmarcolino** [comment]
@uvjustin I upgraded homeassistant to  2020.12.1 and your code to the latest and the issue is gone.

**Comment by csmarcolino** [comment]
Closing the issue, tks
