### ISSUE TITLE
Error After update 5 days ago.

### ISSUE THREAD

**Issue by jermstheitguy** [uvjustin/alarmdotcom#25]
Just installed today and recieving error stating

Logger: homeassistant.components.homeassistant
Source: components/homeassistant/__init__.py:113
Integration: Home Assistant Core Integration (documentation, issues)
First occurred: 1:27:15 PM (1 occurrences)
Last logged: 1:27:15 PM
Platform error alarm_control_panel.alarmdotcom - No module named 'pyalarmdotcomajax'

**Comment by uvjustin** [comment]
For some reason your HA is not installing the pyalarmdotcomajax dependency correctly. This has been reported by several others, but I don't think this is a problem with the component per se as the pypi requirement is spelled out properly in the manifest.json file. I have also never encountered this problem on my install. Are you using hassio? HACS?

**Comment by kc8pnd** [comment]
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.13
hassio | true
host_os | Ubuntu 18.04.1 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.15.0-123-generic
python_version | 3.8.5
supervisor | 2020.12.2
timezone | America/Goose_Bay
version | 0.115.2
virtualenv | false

Currently same error! Thanks for any updates with a fix.

**Comment by uvjustin** [comment]
This is the same issue mentioned here https://github.com/uvjustin/alarmdotcom/issues/14 and here https://github.com/uvjustin/alarmdotcom/issues/19 . No idea why it happens on some installs - it doesn't happen for me or for @aechelon .
A workaround is to just install the pyalarmdotcomajax library using pip.

**Comment by uvjustin** [comment]
@kc8pnd @jermstheitguy Still having this problem?

**Comment by NovaViper** [comment]
Im having this issue too, I just isntalled the raspi4 docker image of Home Assistant Core

**Comment by jermstheitguy** [comment]
I did the work around.  Just installed pyalarmdotcomajax library.
