### ISSUE TITLE
Unable to extract system id from Alarm.com

### ISSUE THREAD

**Issue by sargonas** [uvjustin/alarmdotcom#26]
I restarted my system today, after not making any changes (to the best of my knowledge) to anything related to the alarmdotcom module, but it suddenly stopped working with the following errors in my log:

2020-12-08 11:58:14 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract system id from Alarm.com
2020-12-08 11:58:14 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up alarmdotcom platform for alarm_control_panel
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 85, in async_setup_platform
await alarmdotcom.async_login()
File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 133, in async_login
await self._alarm.async_login()
File "/usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 143, in async_login
self._systemid = json["data"][0]["id"]
KeyError: 'data'

Thoughts? It's been working without issue for about 6 months up until now, and I've manually added this repo to my HACS integration repositories to help keep it up to date.

**Comment by uvjustin** [comment]
I'm not sure what that is from - I haven't seen a similar problem on my end yet. What ADC provider do you use? Have you noticed any changes to the web portal?

**Comment by sargonas** [comment]
I have Protection1 which is a subset of ADT.  Admittedly I’ve only logged
in the web version probably two or three times… And not at all in the past
five months, so I couldn’t say for certain if anything has changed or not.

Would you like me to send you a sanitized screenshot of what the portal
looks like, so you can see if anything seems out of the ordinary?

**Comment by uvjustin** [comment]
I see. It looks like an ADT issue. Try setting `adt: true` in your config. See https://github.com/uvjustin/alarmdotcom/issues/21

**Comment by sargonas** [comment]
sadly I've already tried both true and false settings with the same results, but my pains do read very similar to that thread in many ways, but it looks like resolutions are inconsistent based on the whims of ADT so I guess there's no real answer for now. :(

**Comment by jxbrown** [comment]
@sargonas - I'm having the same issue and using Protection 1. Check out my post #21 

Hoping we get this resolved.

**Comment by uvjustin** [comment]
I see...looks like it's a Protection 1 issue that is similar but maybe distinct to the ADT issue.
I don't want to keep making workarounds for every ADC provider, but since Protection 1 is a big provider and also because this might be very similar to the ADT issue, I'm willing to try and make a workaround for this.
Can one of you guys send me a temporary login to play with?

**Comment by uvjustin** [comment]
I posted a PGP key here https://github.com/uvjustin/alarmdotcom/issues/21#issuecomment-726454739 or alternatively you can PM me on the HA community forum

**Comment by sargonas** [comment]
Sure thing. I have a separate delegated login that I use for my devices
devices, we change the password on that today and I will send it to you
directly for testing.

For what it’s worth, I can’t be 100% certain, but I’m under the impression
that ADT and protection1 have the same login experience. When I login, all
the banners and logos say a ADT and protection1 in the same line, and the
URLs changed to a ADT urls.

**Comment by jxbrown** [comment]
@uvjustin @sargonas  - Thanks for looking into this! Please let me know if you need anything from me.

@uvjustin - I'll close the other issue I created yesterday.

**Comment by uvjustin** [comment]
When I had a look at this yesterday the Protection1 site exhibited a hybrid ADT/ADC style login, while today it seemed to work with the old ADC style login.
Anyway, I did some refactoring and made a new Protection1 login class. It attempts to try the new hybrid login and falls back to the default ADC style login if it doesn't work. Let me know if it works on your end.

**Comment by uvjustin** [comment]
@mikesalz There was a bit of refactoring to share code between the ADT and the protection1 login types. Let me know if you encounter any issues with this updated version.

**Comment by jxbrown** [comment]
@uvjustin Thanks for working on this. I'm getting the following error when I add the protection1 flag. 

**Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:383
Integration: Hass.io (documentation, issues)
First occurred: 8:47:34 AM (1 occurrences)
Last logged: 8:47:34 AM

Invalid config for [alarm_control_panel.alarmdotcom]: [protection1] is an invalid option for [alarm_control_panel.alarmdotcom]. Check: alarm_control_panel.alarmdotcom->protection1. (See ?, line ?).**

Here's my Configuration. yaml section:

**alarm_control_panel:
  - platform: alarmdotcom
    username: xxxx
    password: xxxx
    code: "01234"
    force_bypass: "true"
    no_entry_delay: "home"
    silent_arming: "false"
    protection1: true**

Here's my folder layout:

![image](https://user-images.githubusercontent.com/50732522/102018586-03b0cc00-3d23-11eb-8609-739db2f202a6.png)

**Comment by sargonas** [comment]
That did the trick for me, thanks so much for the quick turnaround @uvjustin!

**Comment by sargonas** [comment]
@jxbrown you want to make sure you install the latest version that includes his fix, restart the HA instance to fully load it, and THEN add the P1 config parameter. If you try to add the it before you restart the instance, the system will have no concept of that function, and block you to prevent a potentially  invalid config from being loaded.

**Comment by jxbrown** [comment]
@sargonas Deleted the previous files alarmdotcom. I downloaded new files per the readme and copied the files into the custom_components directory. Rebooted and the server.  For testing, when I add the adt flag, I don't see error. 

Can you share what your configuration. yaml and alarmdotcom directory looks like?

How did you install the latest version?

Thanks,

**Comment by sargonas** [comment]
Interesting. I had the exact same problem you did when I mistakenly tried
to add the parameter at the same time I updated to the latest version… And
when I rebooted, it worked fine, so I assumed you were in the same boat.

If it’s giving that error it means the code you have loaded for the module
doesn’t have his new function included. If you grab the latest files from
his github obviously that shouldn’t be a problem though… But it seems it is?

For what it is worth, I pasted his repository URL into HACS as a custom
integration, and I update and maintain it from there rather than moving
files manually.

**Comment by jxbrown** [comment]
@sargonas Thanks for the feedback. I moved the alarmdotcom sections higher in my configuration. yaml and it's now working.

**Comment by mikesalz** [comment]
> @mikesalz There was a bit of refactoring to share code between the ADT and the protection1 login types. Let me know if you encounter any issues with this updated version.

@uvjustin Looking good so far. I’ll let you know if any weirdness happens.

**Comment by jxbrown** [comment]
@uvjustin Looking good on my side as well. Thanks for the quick turnaround!

@mikesalz @sargonas - Thanks again for your help.

**Comment by uvjustin** [comment]
Glad it seems to be working for everyone, will close this now.
