### ISSUE TITLE
Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [uvjustin/alarmdotcom#27]
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by uvjustin** [comment]
I don't know anything about CI - what are the benefits of doing that? Can you point me to a good primer?

**Comment by KTibow** [comment]
CI is formatting or validation steps that can happen when stuff happens, like when someone makes a PR or you push. [Here's a primer](https://dev.to/aliahsan07/a-primer-on-github-actions-24l), but you don't need to know anything in order to use it.

**Comment by uvjustin** [comment]
Thanks for the info and the offer. My initial thinking is that it there isn't a pressing need for it now as we don't get a lot of PRs and we also don't have any tests set up, but I will look into it more when I have some time.

**Comment by KTibow** [comment]
Got it. flake8, HACS, and hassfest don't need to set up anything in order to work.

**Comment by uvjustin** [comment]
Closed via https://github.com/uvjustin/alarmdotcom/pull/48
