### ISSUE TITLE
Arm+Stay failed with HTTP code 422

### ISSUE THREAD

**Issue by arungpillai** [uvjustin/alarmdotcom#32]
I am able get the status into HA and also disarm without error. However, when I try to arm it fails.   On the alaram.com panel I don't use any code to arm. 

Arming parameters: force_bypass = True, no_entry_delay = True, silent_arming = True
10:06:42 AM – /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py (ERROR)

Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:315
First occurred: 10:06:42 AM (1 occurrences)
Last logged: 10:06:42 AM

Arming parameters: force_bypass = True, no_entry_delay = True, silent_arming = True

Arm+Stay failed with HTTP code 422
10:06:42 AM – /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py (ERROR)

Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:314
First occurred: 10:06:42 AM (1 occurrences)
Last logged: 10:06:42 AM

Arm+Stay failed with HTTP code 422

**Comment by uvjustin** [comment]
Likely the same as https://github.com/uvjustin/alarmdotcom/issues/31 . Not all systems can use all options/combinations of options to arm. This limitation is from ADC and your alarm system, not from the integration.
To confirm this, try to arm your system from the ADC portal using force_bypass, no_entry_delay, and silent_arming. I'm guessing it won't work.

**Comment by arungpillai** [comment]
Thanks, yes it worked after I removed force_bypass, no_entry_delay, and silent_arming from config you may close this :)
