### ISSUE TITLE
Versioning will be required in future versions of Home Assistant

### ISSUE THREAD

**Issue by brushj** [uvjustin/alarmdotcom#33]
Logger: homeassistant.loader
Source: loader.py:802
First occurred: 4:52:07 PM (1 occurrences)
Last logged: 4:52:07 PM

No 'version' key in the manifest file for custom integration 'alarmdotcomajax'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'alarmdotcomajax'

**Comment by uvjustin** [comment]
Thanks. Just added the version to the manifest file.
