### ISSUE TITLE
Cannot arm

### ISSUE THREAD

**Issue by nuclearheli** [uvjustin/alarmdotcom#36]
Alarm.com integration, ADT. I integrated the code and have a working card on my panel. It successfully logs into alarm.com. When I restart HA I see a successful login on my alarm.com activity monitor. It gather's the correct state of the alarm and shows the usual buttons for Arm Home, Arm Away and Arm Night. Also has one for custom bypass. Not using a code at this time. 

Issue: cannot arm the system from HA. If I arm the system from the web HA gets the proper state and displays the "Disarm". I can press the disarm on HA and it successfully disarms the system.  

I have the new IQ 2 Plus panel and it has the capability to have partitions. I had two partitions on my panel and I thought that was the issue. I removed partition support from the panel and all my sensors were available as one unit. The only option on the web portal was to press arm home or arm away.  Still no luck arming from HA.

Any insight?

**Comment by uvjustin** [comment]
Check that the `force_bypass`, `no_entry_delay`, and `silent_arming` options match (roughly - the text might be slightly different) the settings you use to arm from the portal.

**Comment by nuclearheli** [comment]
Thank you for your response, the issue has been resolved. The force_bypass was the problem. Disabling this eliminated the issue. On another topic, is there any way to get the keypad to come up on the screen only after pushing one of the arming features, or when the disarm is pressed. I must have the code feature for the display but it takes up a lot of real-estate on the panel. It would be nice to be able to push one of the arm features, or the disarm feature and have the keypad presented to the user to enter the code, then send the command to alarm.com after entering the correct code.

**Comment by uvjustin** [comment]
That's more of a HA question - try the forums https://community.home-assistant.io/
