### ISSUE TITLE
alarmdotcom entity not available in alarm panel card with 2fa off

### ISSUE THREAD

**Issue by sdi72** [uvjustin/alarmdotcom#38]
I installed from hacs and followed setup
Logged into alarm.com, setup 2fa, found key
Setup config.yaml and restarted
Everything worked and I could add the entity in the alarm panel card
BUT
I was getting a phone notice of web login every 30 seconds

Logged into alarm.com and disabled 2fa
Restarted HA and received (1) phone notice of web login
Entity no longer available in alarm panel card

**Comment by sdi72** [comment]
2fa still disabled and still getting alerts every 30 seconds of web login. I can disable the alerts but concerned alarm.com will disable access due to login frequency. Removed from config.yaml until resolved.

**Comment by uvjustin** [comment]
This is not an issue with the component. The component works by logging in to the portal for you to keep HA updated with the system status. If you have it set up to send you alerts upon login, you will end up getting a lot of alerts.

**Comment by sdi72** [comment]
> If you have it set up to send you alerts upon login, you will end up getting a lot of alerts.

Thank you for the reply, and I agree the component works by logging in.
The statement above indicates it is normal for alarmdotcom to need to re-login every 30 seconds (to keep HA updated). I was hoping there was a "keep logged in" or other setting to reduce this need. I am concerned I'll be flagged and disabled for that much activity, like API restrictions. I would prefer to keep new web login notifications on to know if a new device is trying to login. Has anyone reported being disabled for excess logins? Thanks again and thanks for the component.

**Comment by uvjustin** [comment]
I haven't heard about anyone who has had their account disabled using the default settings.
