### ISSUE TITLE
cannot load state data from Alarm.com

### ISSUE THREAD

**Issue by SkyHyperV** [uvjustin/alarmdotcom#39]
Is the issue below normal? My alarm still operates via my automations but curious if I'm missing something that needs to be configured to remove the error.

WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.alarm_com is taking over 10 seconds
ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com

**Comment by aechelon** [comment]
Oddly I saw the same error yesterday evening, after which I was unable to set the alarm state. 
Restarting HA restored the ability to set the alarm state, however I'm seeing this in the log:

Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:135
First occurred: 8:31:54 AM (295 occurrences)
Last logged: 10:59:24 AM

Unable to extract system id from Alarm.com

===========

Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:181
First occurred: 1:41:56 AM (296 occurrences)
Last logged: 10:59:24 AM

Unable to extract state data from Alarm.com

===========

Update for alarm_control_panel.alarm_com fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 166, in async_update
    self.sensor_status = json["data"]["attributes"]["needsClearIssuesPrompt"]
KeyError: 'data'

===========

I haven't debugged it yet, but I updated the plugin to the latest and HA to 5.13 a few days ago. I suspect one of those maybe the culprit.

**Comment by uvjustin** [comment]
@SkyHyperV this is the same as what was asked in #35. It's quite normal to see this message a handful of times a day, but any more than that and I would look into connectivity problems on your HA machine.
@aechelon have you enabled 2fa and updated your config with the cookie? Just yesterday my portal finally prompted me to use 2fa. Only clicking skip would probably result in errors like what you are seeing.

**Comment by aechelon** [comment]
@uvjustin, thanks for the heads up.  Although the Brinks site has a 2FA setup option, it hasn't prompted with the nag screen yet.
Would you recommend setting it up even if it's not prompting for it?

**Comment by uvjustin** [comment]
@aechelon I would just go ahead and do it since it only takes a minute or two and it seems like eventually all the portals will nag for 2fa.

**Comment by aechelon** [comment]
@uvjustin yep, that was it, thanks!

**Comment by uvjustin** [comment]
@aechelon Should we add some kind of notice/troubleshooting section to tell users to try 2FA if they encounter errors?
Regarding the "Can not load state data" message, I will probably lower the log level to `Warning` or even `Debug`. I think most people will have the occasional connection error from time to time and `Error` messages seem to freak people out. Any thoughts on that?

**Comment by adrian97c** [comment]
Will this work for SmartThings?

**Comment by uvjustin** [comment]
This is a custom component for Home Assistant - it has nothing to do with SmartThings unfortunately.
