### ISSUE TITLE
Connected Car Feature Request

### ISSUE THREAD

**Issue by pdobrien3** [uvjustin/alarmdotcom#40]
Curious if there is any interest in adding this:
https://support.suretyhome.com/t/getting-started-with-alarm-com-connected-car/13993

**Comment by uvjustin** [comment]
Looks pretty neat. Unfortunately I won't be getting one anytime soon so will be hard for me to do anything - happy to look at PRs for this though.

**Comment by elahd** [comment]
@pdobrien3 Do you have one of those? If you do, can share a dump of your alarm.com response data to help us understand how those devices are handled?

You'll need some comfort with the command line to do this. You'll also need Python >=3.9 installed.

1. Install pyalarmdotcomajax v0.2.0-beta via pip: `pip install pyalarmdotcomajax==0.2.0b0`
2. Run `adc -u YOUR_USERNAME -p YOUR_PASSWORD -c YOUR_2FA_COOKIE -v`

Skip the 2FA parameter if you don't have two factor authentication enabled.

You also may want to scrub any private info before posting the results. That command should _not_ return your name, email address, etc., but it will output sensor names and may output GPS data from your car sensor.

**Comment by pdobrien3** [comment]
Sorry. I don’t have one yet. I prob wouldn’t get one until it is supported.

**Comment by elahd** [comment]
Got it. Someone has to be the first to bite the bullet! Closing until a volunteer with the device comes along.
