### ISSUE TITLE
alarmdotcom

### ISSUE THREAD

**Issue by bkr1969** [uvjustin/alarmdotcom#41]
Is this component working at all?  I installed through HACS but there is no alarm_control_panel in my list of entities.

**Comment by fredclausen** [comment]
Works fine for me and has been doing for quite some time.

**Comment by adamyoung3** [comment]
Be sure to input the yaml configuration. If your not using 2fa, I suggest you add a new account to alarm.com and enable 2fa on that make it a dedicated home assistant account.

**Comment by bkr1969** [comment]
I have 2fa on my account. I have the three lines added to my config. I’ve reinstalled and re-started multiple times but there is no alarm_control_panel entity anywhere. Is there anything else I need to do when installing besides adding to the config?

**Comment by aechelon** [comment]
Working fine for me as well.  
Can you see the custom component directory listed in your config directory (i.e. config\custom_components\alarmdotcom)?
What does your config look like?
Do you see any warnings in the logs that might indicate that the component is being started?

**Comment by bkr1969** [comment]
I do see the alarmdot com folder in the custom components directory. config is:
``alarm_control_panel:
  platform: alarmdotcom
  username: bkr1969
  password: !secret alarm
``
I see absolutely nothing relating to alarmdot com in any log

**Comment by bkr1969** [comment]
So, I know the integration is installed because when I went to HACS today, I got a message to update the integration. I did, restarted but still no alarm_control_panel in my list of entities.

**Comment by bkr1969** [comment]
Does anyone have any idea? It bothers me that my alarm system doesn't work anymore, but it bothers me more that apparently this integration is working for others.
I added the integration through HACS and added the three lines to my config file. I restarted HA but I have no alarm_control_panel entity and cannot add an alarm card to my dashboard.  What step am I missing?  I initially thought the problem could be an instability on my RPi, but I've been running on the new HA Blue for a month now and everything else works great. Please give me some input.

**Comment by bkr1969** [comment]
Now I'm getting this error:
Platform error alarm_control_panel.alarmdotcom - cannot import name 'AlarmdotcomProtection1' from 'pyalarmdotcomajax' (/config/pyalarmdotcomajax.py)

Where even is the pyalarmdotcomajax.py file? I don't see it anywhere in the repository.

**Comment by bkr1969** [comment]
OK...so I never could find my 2FA cookie (probably could if I spent a little more time/effort) so I disabled 2FA on my account and the integration works fine.

**Comment by dinomite** [comment]
I don't have 2FA on my account, but I did get the `twoFactorAuthenticationId` cookie. This component doesn't work for me with or without the cookie specified in the configuration. The error I get is:

```
2021-07-16 15:19:14 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract system id from Alarm.com
2021-07-16 15:19:14 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up alarmdotcom platform for alarm_control_panel
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 96, in async_setup_platform
await alarmdotcom.async_login()
File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 156, in async_login
await self._alarm.async_login()
File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 206, in async_login
return await self._async_get_system_info()
File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 166, in _async_get_system_info
self._systemid = json["data"][0]["id"]
KeyError: 'data'
```

**Comment by uvjustin** [comment]
@bkr1969 Glad you got it working.
@dinomite Try setting up 2FA on the login you use for the component.

**Comment by dinomite** [comment]
@uvjustin That worked, thank you. What do you think about changing the instructions (#43)?
