### ISSUE TITLE
Arming without code input

### ISSUE THREAD

**Issue by grayjetmedia** [uvjustin/alarmdotcom#42]
Good Afternoon.  Awesome plugin. I've been attempting to get this plugin to allow for arming the alarm without inputting the code and am having zero luck.  I am confident the code in the code section is correct.

Configuration.yaml looks like this:
>alarm_control_panel:
  platform: alarmdotcom
    username: !secret alarmdotcom-username
    password: !secret alarmdotcom-password
    code: !secret alarmdotcom-code
    force_bypass: "false"
    no_entry_delay: "false"
    silent_arming: "false"
    two_factor_cookie: !secret alarmdotcom-2FA

Secrets.yaml
>alarmdotcom-username: username
alarmdotcom-password: asdfghjkl
alarmdotcom-2FA: "AABBCCDD"
alarmdotcom-code: "1234"

Customize.yaml
>alarm_control_panel.alarm_com:
    code_arm_required: false

Any reason why this wouldn't be working?  Error log just says:

> 2021-07-12 16:32:30 WARNING (MainThread) [custom_components.alarmdotcom.alarm_control_panel] Wrong code entered

Other errors I'm seeing that I don't think are related are:

> 2021-07-12 18:38:06 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
2021-07-12 18:38:28 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
2021-07-12 18:38:58 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract state data from Alarm.com

**Comment by StarFox2873** [comment]
Just remove the code from your yaml.  The force bypass, no entry and silent arming arent always compatible so try it without that.  


alarm_control_panel:
  - platform: alarmdotcom
    username: Yourusername 
    password: !secret alarmdotcom
    # The below parameters are optional
    #  code: "01234"
    # force_bypass, no_entry_delay, and silent_arming are not supported on all systems/providers. See the description section below.
    # two_factor_cookie is only used if your portal is forcing 2FA
    two_factor_cookie: "your cookie"

**Comment by uvjustin** [comment]
@grayjetmedia Did you get it working? As @StarFox2873 mentioned, remove the "code" section. That is just for if you want to have to enter a code in the frontend to arm/disarm and has nothing to do with the code on the alarm panel.

**Comment by grayjetmedia** [comment]
Yes indeed.  I pulled out the code as described and it's all working as expected.  Thanks to both for following up.
