### ISSUE TITLE
Tons of template variable warnings in logs

### ISSUE THREAD

**Issue by sargonas** [uvjustin/alarmdotcom#47]
Ever since HA added the new templating system and turned on warnings for it's variables, my logs are regularly filled every 20 to 30 minutes with a string of warnings, one for each alarmdotcom sensor I have (door openings and motion sensors). As far as I can remember from setting this up, I am *fairly* certain that I did not ever create anything custom that uses this, so I wanted to confirm here if this is indeed stemming from original code in the module and if it's something that can be fixed on this side.

Here's an example of one of them:

`2021-09-24 03:52:36 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'TRUE' is undefined when rendering '{{ state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Front Door is Open', ignorecase=TRUE) }}'`

I was going to start poking through the repo as well and look for where this might be and see if perhaps I can't make a PR to fix it myself, but figured I would start a conversation here before I go too far down the rabit hole in case you have a quick answer or can confirm this is not cause by your code and something custom I've forgotten about. :)

**Comment by bkr1969** [comment]
I am completely unable to pull the states of my sensors from alarm.com. I repeatedly get these errors:
```
2021-09-24 08:47:35 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
2021-09-24 08:48:01 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract state data from Alarm.com
```
and all of my binary sensors show as off regardless of whether the door/window is open or closed.  How did you even get the states to begin with?

**Comment by sargonas** [comment]
Oh, interesting. I don't know really... mine has "just worked" as expected ever since I installed it?

I do know that the online system provides slightly different formatted info depending on which specific service provider and platform you have. In my case it is the protection1  sub-entity of ADT￼￼

**Comment by bkr1969** [comment]
I bet that's the issue.  I'm through Brinks.

**Comment by sargonas** [comment]
Found the issue, it was actually some custom code I dropped in my configuration.yml EONS ago and forgot about, and had no idea was there. Was my fault all along!
