### ISSUE TITLE
New to Home Assistant

### ISSUE THREAD

**Issue by Markian777** [uvjustin/alarmdotcom#49]
Hello all! Im new to Home Assistant and I have been at ADC for 3 days now and have had to restart my raspberry pi because I deleted something I shouldn't have.

Anyways! Could I get some clarification about how to set this up more?

Where and what format does the "Description of configuration parameters" need to go?

I have everything downloaded via HACS and typed this into configuration..yaml:

# Example configuration.yaml entry
alarm_control_panel:
  - platform: alarmdotcom
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    code: "01234"
    force_bypass: "true"
    no_entry_delay: "home"
    silent_arming: "false"
 
Gives me this notification:
This entity ('alarm_control_panel.home') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail. 

You can overwrite some attributes in the entity customizations section.

**Comment by bfish2** [comment]
I implemented my alarmdotcom a couple days ago, but don't see any state changes in any of my door sensors.  I do see state changes in my motion sensor, but it appears to only see some of the motion detected.  I found this issue log and triple checked my config.yaml entries against these above and they are letter perfect.  Any thoughts what else might be going on or where else I should be looking?  I am able to arm/disarm, so I believe i am logged in succesfully via the integration.   Thanks!

**Comment by Markian777** [comment]
This might sound silly, but if you leave your door open for—let’s say 10-15 minutes—will it show a change of state?

I notice that Alarm.com is incredibly slow to update the states, and it has nothing to do with the integration, but just Alarm.com.

**Comment by rintaran** [comment]
> I implemented my alarmdotcom a couple days ago, but don't see any state changes in any of my door sensors. I do see state changes in my motion sensor, but it appears to only see some of the motion detected. I found this issue log and triple checked my config.yaml entries against these above and they are letter perfect. Any thoughts what else might be going on or where else I should be looking? I am able to arm/disarm, so I believe i am logged in succesfully via the integration. Thanks!



> This might sound silly, but if you leave your door open for—let’s say 10-15 minutes—will it show a change of state?
> 
> I notice that Alarm.com is incredibly slow to update the states, and it has nothing to do with the integration, but just Alarm.com.

I can confirm, alarm.com is very slow to update states. I'm generally seeing a 5-10 minute delay, so not as bad as Markian, but still quite significant.

**Comment by bfish2** [comment]
Yes, it does seem slow in the alarm.com app on my phone, but the events are showing up there within a minute or two .  Yet, I'm still not seeing any opens on either of the doors that I have been using all day on HA.  I am looking in History.  Should I be exploring somewhere else?

**Comment by rintaran** [comment]
I noticed that unless the door was open for 5-10 minutes, it won't even register as having been opened via HA. It's a significant delay, and requires it to be open for a consistent period. This may have something to do with how this addon scrapes the site. I imagine if it scraped it too often, it would get flagged as some form of malware, so a 10-minute delay between checks may be part of the coding. If that's the case, unless the door was still open when the check occurred, HA would never receive notice that it had been opened.

Sadly, that's about as far as I can go here. I'm not a coder and am learning right from ground level.

**Comment by bfish2** [comment]
Thanks all!  I will give it a try leaving the door open a while.  If that is the case it kind of defeats the purpose of using alarmdocom for me.  Oh, well, live and learn!

**Comment by uvjustin** [comment]
I'm not sure what the delay from devices to the ADC portal is, and the delay may actually differ by system or even by device. The integration actually fetches the state from the portal every 30 seconds, so it's not instantaneous but it should add more than a minute to any other delay. Of course this is not too suitable for some purposes, like detecting doors or windows opening. I think the best use of this integration is to view whether a system is armed or not and to send arming or disarming commands.
As for the motion sensors vs doors/windows, motion sensors will end up staying triggered for a period of time rather than turning on and off instantly like doors/windows. That should explain why our 30 second interval will pick up a motion event but not a door event. I think this behavior for motion sensors makes it more useful for most people as they won't turn on and off when someone starts and stops moving. This behavior is not added by this integration but comes from ADC itself.
