### ISSUE TITLE
LinkInteractive Alarm.com error on restart and constant login messages

### ISSUE THREAD

**Issue by jeremysouthard** [uvjustin/alarmdotcom#52]
I've added the alarmdotcom integration via HACS and followed the instructions to modify the configuration.yaml file.  Here's the relevant section:
```
alarm_control_panel:
  - platform: alarmdotcom
    username: !secret alarm_username
    password: !secret alarm_password
```

I have confirmed the username and password in my secrets.yaml are correct.

When I restart Home Assistant, I get the following log entries:
```
Logger: homeassistant.components.alarm_control_panel
Source: custom_components/alarmdotcom/alarm_control_panel.py:156
Integration: Alarm control panel (documentation, issues)
First occurred: 10:22:02 AM (1 occurrences)
Last logged: 10:22:02 AM

Error while setting up alarmdotcom platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 96, in async_setup_platform
    await alarmdotcom.async_login()
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 156, in async_login
    await self._alarm.async_login()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 206, in async_login
    return await self._async_get_system_info()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 166, in _async_get_system_info
    self._systemid = json["data"][0]["id"]
KeyError: 'data'
```

And my email gets spammed with emails letting me know there was a successful login.  After 3 restarts, I now have 177 emails.  

Am I missing something with the configuration?  My provider is Link Interactive.  I tried adding `adt: true` and that actually failed the login (as I expected).

**Comment by uvjustin** [comment]
Did you configure 2FA?

**Comment by jeremysouthard** [comment]
I do not have 2FA setup.

**Comment by uvjustin** [comment]
Try setting it up, quite a few similar issues in the past have been resolved that way.
https://github.com/uvjustin/alarmdotcom/issues/34
https://github.com/uvjustin/alarmdotcom/issues/39
https://github.com/uvjustin/alarmdotcom/issues/41

**Comment by jeremysouthard** [comment]
Setting up 2FA worked, thanks.  Sorry my issue search terms were centered around the carrier instead of the error.  I should have found that myself without having to open an issue.
