### ISSUE TITLE
Lock support

### ISSUE THREAD

**Issue by vegardengen** [uvjustin/alarmdotcom#54]
Hi,

I was going to ask about supporting locks. Then, I started looking at the code.

I have now made this dual personality, both a home assistant lock and an alarm. The accompagnying pyalarmdotcomajax also had to be modified.

This now works in my home assistant, but I need to wrap it up and maybe do some small refactoring before I submit a pull request.

**Comment by Raul-7-7** [comment]
Thanks for this.
