### ISSUE TITLE
Not connecting anymore 

### ISSUE THREAD

**Issue by firstdominator** [uvjustin/alarmdotcom#57]
Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:375
First occurred: 11:09:10 PM (1 occurrences)
Last logged: 11:09:10 PM

Arming parameters: force_bypass = True, no_entry_delay = True, silent_arming = True

And this error as well.

Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:374
First occurred: 11:09:10 PM (1 occurrences)
Last logged: 11:09:10 PM

Arm+Stay failed with HTTP code 422

Thanks

**Comment by uvjustin** [comment]
Probably the same as https://github.com/uvjustin/alarmdotcom/issues/32 . Also see the comment regarding those options in the example configuration.yaml
Please use the HA forum for tech support questions - github issues should be for bugs.
