### ISSUE TITLE
Integration quit working again

### ISSUE THREAD

**Issue by bkr1969** [uvjustin/alarmdotcom#58]
No changes in version or core or anything else, just stopped working.  On HA restart the entity is "not available."

**Comment by uvjustin** [comment]
Nothing has changed in this component either.
You haven't included much information, but this is likely similar to many other issues including #34, #39, #41, and #52.
Please set up 2FA as [detailed in the readme](https://github.com/uvjustin/alarmdotcom#two-factor-authentication), and please use the [HA community site](https://community.home-assistant.io/c/third-party/15) for future troubleshooting unless you're sure there's a bug here.

**Comment by bkr1969** [comment]
Apparently my security company suddenly decided to require 2FA without letting me know.  I added the cookie and it worked. Thanks!
