### ISSUE TITLE
device_state_attributes in Logs (after latest version)

### ISSUE THREAD

**Issue by Raul-7-7** [uvjustin/alarmdotcom#61]
Hi, I upgraded to the latest version (0.1.11 - d4b5f84) , and noticed this entry in my log. Everything seems to be working, so not a bug, just reporting it! 
PS) Thank you for this awesome integration.

**Entity alarm_control_panel.alarm (<class 'custom_components.alarmdotcom.alarm_control_panel.AlarmDotCom'>) implements device_state_attributes. Please report it to the custom component author.**

HA version: core-2021.12.1

**Comment by Raul-7-7** [comment]
https://github.com/uvjustin/alarmdotcom/issues/55 same issue, however it is not fixed for me at least on the latest version.

**Comment by uvjustin** [comment]
Thanks, that's odd, I made the change and even put it in the changelog, but I guess somehow the change got lost. I'll update it now, but I won't change the version so it might not be updated in HACS until later.

**Comment by Raul-7-7** [comment]
Thx! @uvjustin 
If I recall correctly, HACS is not going to pick up unless you change version, so if anyone wants to update (that has updated already), best is re-install in HACS once the changes are applied.
