### ISSUE TITLE
Releases and Release Notes

### ISSUE THREAD

**Issue by Nealtron** [uvjustin/alarmdotcom#64]
Would it be possible to publish releases with release notes in order to populate the change-log within HACS?

How alarmdotcom updates appear to HACS right now:
![image](https://user-images.githubusercontent.com/6655394/148564180-278cc2fa-8d71-4e84-8782-6ff9fd469aa0.png)

How other add-ons appear in HACS:
![image](https://user-images.githubusercontent.com/6655394/148564242-0cca3ce4-e1f4-43d0-9156-f983bc2010f5.png)

Github has documentation on tagging releases: https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

**Comment by elahd** [comment]
I re-published the most recent release via GitHub releases... although it looks like this is forcing everyone to perform a needless update.

So consider this fixed on a go-forward basis 🤦🏼‍♂️.

**Comment by Nealtron** [comment]
Thank you!
