### ISSUE TITLE
Lock status stuck in 'Malfunction'

### ISSUE THREAD

**Issue by mjmicks** [uvjustin/alarmdotcom#79]
Nothing reported in the logs. Lock commands work as expected, but the status continues to only display "Malfunction"

EDIT: running beta 5.

**Comment by mjmicks** [comment]
Should note: I'm running beta 5

**Comment by elahd** [comment]
This was fixed as part of uvjustin/pyalarmdotcomajax#31, which just went out as beta 6 of this integration. Can you update and report back?

**Comment by mjmicks** [comment]
Updating to beta 6 fixed my lock status. Appreciate all the work!
