### ISSUE TITLE
Integration does not show up despite being added

### ISSUE THREAD

**Issue by AritroSaha10** [uvjustin/alarmdotcom#80]
Hi,

After installing the HACS integration, it doesn't seem to appear in the Integration list under "Set up a new integration". However, using the yaml configuration seems to work (though with a warning). Since this is my first time using the integration, is this happening due to a mistake on my behalf or a bug? TIA

Integration list after installing HACS integration:
![image](https://user-images.githubusercontent.com/29025984/151683347-3472c0c7-890c-41b2-bbef-2bba41df1c33.png)

Integration installed in HACS:
![image](https://user-images.githubusercontent.com/29025984/151683352-7380831c-db2c-4909-85d7-0b48ec955059.png)

Logs saying that the setup has been migrated to the Integrations page, even though it has not:
`2022-01-29 20:31:16 WARNING (MainThread) [custom_components.alarmdotcom.alarm_control_panel] Configuration of Alarm.com via configuration.yaml is deprecated and will be removed in a future release. Your existing configuration has been migrated to the integrations page successfully and can be removed from your configuration.yaml file.`

**Comment by travisllwork** [comment]
Just adding to this as I have the same issue.

**Comment by mjmicks** [comment]
Make sure to clear browser cache and restart HA. Does the trick for me.

**Comment by AritroSaha10** [comment]
> Make sure to clear browser cache and restart HA. Does the trick for me.
Worked perfectly, thank you!

**Comment by hufman** [comment]
In my case, HACS claimed the previous install of alarmdotcom was up-to-date (0.2.1), but the actual files showed that it was using my previously-installed 0.1.12 version. I uninstalled and reinstalled it through the HACS interface and it popped right into the Integrations list.
