### ISSUE TITLE
Not finding Intergration?

### ISSUE THREAD

**Issue by nicocoetzee** [uvjustin/alarmdotcom#81]
Hello - 

I installed this via HACS and after the restart, I don't see Alarm.com in the Integration (Configuration) section?

Any help will be appreacted.

Many thanks,
n.

**Comment by jason-oliver** [comment]
I'm also seeing this issue.  Confirmed its showing as downloaded by HACS, restarted HA, but not showing up when I try to add integration.

**Comment by DannoPeters** [comment]
I'm having this issue as well. Looking forward to finding a solution.

**Comment by CastleSeven** [comment]
Same here. 

![image](https://user-images.githubusercontent.com/965241/151908781-9ef5d5be-fcc4-469d-b4be-e05a187dc4e3.png)

![image](https://user-images.githubusercontent.com/965241/151908815-1613f1a8-bedf-4910-adf1-c675a18ce771.png)

**Comment by MvdenE** [comment]
I'm having this issue as well.  Fresh install hass and hacs.

**Comment by DannoPeters** [comment]
I got mine working!!!!! 😄 🎉
After reading this Reddit post https://www.reddit.com/r/homeassistant/comments/oxdkhi/custom_integration_in_hacs_not_showing_up/

I cleared my web browsers cache and did a hard reset (unplugged) my Home Assistant for a few minutes.

Hopefully, this helps with everyone else's installation issues as well. 

Looking really forward to using this integration, thanks to all the Devs who built and are maintaining this repo. 
![alarmcom sucess](https://user-images.githubusercontent.com/22260702/151919621-8ffa0af3-c1c3-435f-86cb-f55434b21586.png)

**Comment by jason-oliver** [comment]
> I got mine working!!!!! 😄 🎉 After reading this Reddit post https://www.reddit.com/r/homeassistant/comments/oxdkhi/custom_integration_in_hacs_not_showing_up/
> 
> I cleared my web browsers cache and did a hard reset (unplugged) the box running my Home Assistant for a few minutes.
> 
> Hopefully, this helps with everyone else's installation issues as well.
> 
> Looking really forward to using this integration, thanks to all the Devs who built and are maintaining this repo.
> 
> ![alarmcom sucess](https://user-images.githubusercontent.com/22260702/151919621-8ffa0af3-c1c3-435f-86cb-f55434b21586.png)

Tried that on my end didn't work for me :(   Still can't see it in add integrations.

**Comment by mjmicks** [comment]
Clear browser cache and restart HA config. Did the trick for me.

**Comment by elahd** [comment]
@jason-oliver Can you try:

1. Uninstall the add-in via HACS
2. Restart Home Assistant
3. Clear browser cache
4. Reinstall the add-in via HACS
5. Restart Home Assistant
6. Try adding the integration from the integrations page.

**Comment by nicocoetzee** [comment]
Hi all.

I unplugged HA to do a reset, uninstalled, clear the browser cache, restarted HA, re-installed, etc. Tried Brave, Chome & Safari, and still don't see it in Integrations:

![Screen Shot 2022-02-01 at 9 03 17 AM](https://user-images.githubusercontent.com/21128291/152015375-a2b58cc1-3697-4e55-a7a1-468ab48493b1.png)

Any additional ideas?

**Comment by jason-oliver** [comment]
> @jason-oliver Can you try:
> 
> 1. Uninstall the add-in via HACS
> 2. Restart Home Assistant
> 3. Clear browser cache
> 4. Reinstall the add-in via HACS
> 5. Restart Home Assistant
> 6. Try adding the integration from the integrations page.

Done,  Didn't fix it :(

**Comment by elahd** [comment]
Shoot, sorry. One more thing:

Can you try adding the below to configuration.yaml, restarting Home Assistant, and checking for any alarmdotcom errors in your Home Assistant logs? If you don't see anything at the top of  your logs page, try hitting the "view full logs" button.

```yaml
logger:
  default: warn
  logs:
    custom_components.alarmdotcom: debug
    pyalarmdotcomajax: debug
```

**Comment by MvdenE** [comment]
![Screenshot_20220201-202754_Home Assistant](https://user-images.githubusercontent.com/89900648/152037560-8087edc5-7615-4bb9-996a-ad643dc96923.jpg)

If have done all the things nothing helped

**Comment by elahd** [comment]
> my other system crashed with no backup😉

Ouch.

That warning shows up for all custom components. Have you added the logger text in my last comment to configuration.yaml? That will reveal a lot more data that will help with debugging.

**Comment by nicocoetzee** [comment]
Hi - I added the debugger and didn't see any additional errors in the log?
![Screen Shot 2022-02-01 at 11 42 15 AM](https://user-images.githubusercontent.com/21128291/152039815-0b89c5c7-51ad-4d27-ac08-cc64d875fe1e.png)
![Screen Shot 2022-02-01 at 11 43 38 AM](https://user-images.githubusercontent.com/21128291/152039818-7aba40c7-f4c2-4bbe-80c7-3b538b2d4a18.png)

**Comment by MvdenE** [comment]
![Screenshot_20220201-211520_Home Assistant](https://user-images.githubusercontent.com/89900648/152044253-8b341810-7c5b-47c7-8966-a2f70c310059.jpg)

Yes I have add it

**Comment by elahd** [comment]
Ok. I have 4 more ideas:

**Check Integration Version**

There are currently two versions of the integration floating around: the v0.1 series and the v0.2-beta series. The v0.1 version is configured entirely via configuration.yaml, but the instructions no longer show up on the main GitHub page. Take a look at the old instructions page at https://github.com/uvjustin/alarmdotcom/tree/v0.1.12. Follow along there to set up the integration via configuration.yaml.

The v0.2-beta versions are configured via the Home Assistant integrations page. If you've installed the beta version, continue along below:


**Different Browser**
Does this work in a different browser?

**Full Chrome Cache Clear**
If you're using Chrome, right click on an empty stop within Home Assistant and click Inspect. Go to the Application tab, then the Storage leftnav entry. Check off all of the circled checkboxes, then hit "clear site data".

![image](https://user-images.githubusercontent.com/466460/152043520-ec5509ce-7785-497b-998e-9fc8f2c00785.png)

**Config Entities**
(You may need to install File Editor from the Home Assistant Add-In Store (not HACS) for this.)

From your Home Assistant root folder, edit /config/.storage/core.config_entries. Search for "alarmdotcom". If you find an entry, delete it. Be careful, though. This file isn't intended to be user editable. You'd want to delete exactly the following:

```json
            {
                "entry_id": "6e829f4843eac5bd512858c23627ff03",
                "version": 1,
                "domain": "alarmdotcom",
                "title": "Watchlight Corporation: redacted",
                "data": {
                    "username": "redacted",
                    "password": "redacted",
                    "2fa_cookie": "redacted"
                },
                "options": {
                    "arm_code": "redacted",
                    "force_bypass": "Always",
                    "no_entry_delay": "Never",
                    "silent_arming": "Never"
                },
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "import",
                "unique_id": "redacted",
                "disabled_by": null
            },
```

If that doesn't work, I'm out of ideas. Try checking the Home Assistant forums for general issues with custom components not showing up in the integrations page. I've seen people report this sporadically with various integrations but haven't followed too closely.

**Comment by MvdenE** [comment]
I found it. Version check did the trick
I had v0.1 now i have v0.2 beta 6 
Clear all cache and there it was

**Comment by nicocoetzee** [comment]
I dont see the .storage/core.config_entries folder?
![Screen Shot 2022-02-01 at 1 55 19 PM](https://user-images.githubusercontent.com/21128291/152057998-6416d2bc-93a7-4c60-96dc-714402e9d71c.png)

**Comment by nicocoetzee** [comment]
> 

I would really appreciate it if you could explain the steps you took to get it working.

**Comment by nicocoetzee** [comment]
> 

I would really appreciate it if you could explain the steps you took to get it working.

**Comment by DannoPeters** [comment]
> Hi all.
> 
> I unplugged HA to do a reset, uninstalled, clear the browser cache, restarted HA, re-installed, etc. Tried Brave, Chome & Safari, and still don't see it in Integrations:
> 
> ![Screen Shot 2022-02-01 at 9 03 17 AM](https://user-images.githubusercontent.com/21128291/152015375-a2b58cc1-3697-4e55-a7a1-468ab48493b1.png)
> 
> Any additional ideas?

Are you able to see the Alarmdotcom files in your "custom_components" folder after downloading through HACS?

![alarm_custom_components](https://user-images.githubusercontent.com/22260702/152069433-3f5322e4-844c-42bd-9054-95d3c72020b1.png)

**Comment by DannoPeters** [comment]
I made up a fresh Home Assistant boot SD for a spare pi4 I had from a drone project. 

### What I tried that didn't work ###
1. Installed HACS
2. Rebooted
3. Pulled the AlarmDotCom repo through HACS (v0.1.12)
4. Rebooted as instructed by HACS
5. :-/ Not visisible couldnt find Alarm.com on the list of integrations
6. Tried a hard reboot (unplugging)
7. Cleared my web cache
8. :-( Still not visisible couldnt find Alarm.com on the list of integrations
9. Tried a buch of other browsers and cleared my cache a few more times for good measure
10. Still no luck :-/

### What I tried that did work ###
1. Removing v0.1.12 through HACS
2. Rebooting through Home Assistant
3. Reinsaling v0.1.12 through HACS
4. Unplugging my Pi and letting it sit unplugged while I made a snack (snack part is optional but highly reccomended ;-)
5. Plugged the Pi back in and the integration was then avalible to be installed. 

I reflashed the SD card and experieced the same behaviour as above. 
@nicocoetzee and @jason-oliver which hardware are you working on? 
Maybe this is a Home Assistant OS or Pi specific work around?

**Comment by nicocoetzee** [comment]
Good morning. I'm running HA OS on a Home Assitant Blue. So not that different from your Pi setup.

This is really weird that it is working for some and the exact same protocol doesn't work for others.

I'll keep on tinkering with it, but don't really know what else to try.

**Comment by elahd** [comment]
@nicocoetzee Which version of the Alarm.com integration are you using? v0.1 or v0.2-beta?

**Comment by nicocoetzee** [comment]
HI @elahd - 

It seems HACS is installing 0.1.12? See below. How can I install 0.2?

![Screen Shot 2022-02-02 at 12 17 46 PM](https://user-images.githubusercontent.com/21128291/152230618-d13847ad-500e-4ef5-a21a-3ddcdf30e321.png)

And really thank you for all your help.

**Comment by elahd** [comment]
Sure thing! That'll do it. v0.2 is still in beta and not as reliable as v0.1. If you check the "Show beta versions" checkbox in your screenshot it should appear in the select version dropdown.

**Comment by nicocoetzee** [comment]
You're AWESOME! That did the trick.
![Screen Shot 2022-02-02 at 3 51 39 PM](https://user-images.githubusercontent.com/21128291/152257302-1ae4a461-b7c5-4fc2-9d91-c8c5e897100c.png)

**Comment by nicocoetzee** [comment]
I'm getting two errors now in the Integration section. I have double-checked my login credentials and 2FA is not enabled. Am I missing something?
![Screen Shot 2022-02-02 at 4 02 30 PM](https://user-images.githubusercontent.com/21128291/152258347-71769a2e-06cc-4fc8-960c-ade64d8234dc.png)
![Screen Shot 2022-02-02 at 4 02 33 PM](https://user-images.githubusercontent.com/21128291/152258351-9607af82-8db2-4978-8165-3efdf5ea1a58.png)

**Comment by elahd** [comment]
Do you see a more detailed error in the logs?

**Comment by nicocoetzee** [comment]
This is all I found:
![Screen Shot 2022-02-02 at 5 36 53 PM](https://user-images.githubusercontent.com/21128291/152266749-6a7c84d7-3854-465c-ab9b-34862924a975.png)

**Comment by elahd** [comment]
Who is your Alarm.com provider?

**Comment by nicocoetzee** [comment]
geoarm.com

**Comment by nicocoetzee** [comment]
Do you think that might be the problem? Who do you guys have as your
alarm.com provider?

**Comment by nicocoetzee** [comment]
I think I potentially know what the problem is. I don't have 2FA enabled and after I log in, it takes me to the screen below, which created the authentication issue for the Integration. I have now enabled 2FA.

Can you please provide a little more info on the step? 
"Copy the cookie string into your config under the `Two Factor Cookie` parameter."

Should this be added in the configuration.yaml? If so, can you please give me an example of the entry?

Thank again for all the support @elahd!

![Screen Shot 2022-02-03 at 7 29 19 AM](https://user-images.githubusercontent.com/21128291/152374305-816201ea-0293-46e3-aa9e-5a91904f3b75.png)

**Comment by nicocoetzee** [comment]
I entered it in the login screen and now it's all working!
![Screen Shot 2022-02-03 at 7 40 40 AM](https://user-images.githubusercontent.com/21128291/152375942-eec714b5-739e-43ef-9089-52866995b66c.png)

**Comment by elahd** [comment]
Awesome, glad you got it working. When you do configure two-factor auth, you'll need to log back in to the add-in with the 2FA cookie. See https://github.com/uvjustin/alarmdotcom#two-factor-authentication-cookie for instructions.
