### ISSUE TITLE
Alarm.com Hundreds of "Successful Web Login" Notifications

### ISSUE THREAD

**Issue by DannoPeters** [uvjustin/alarmdotcom#83]
Hello, I just recently installed the AlarmDotCom integration on my Home Assistant OS.
For clarity I am referring to the integration as AlarmDotCom and the alarm system as Alarm.com 
I have tried this on v0.1.12 and v0.2.0-beta.7

It was great to see all the Alarm.com sensors on my same dashboard and be able to arm and disarm my Alarm.com panels all from one app (Home Assistant).

But the AlarmDotCom integration seems to be repeatedly logging in every minute or so (generating hundreds of notifications) on Alarm.com and totally burring any relevant sensor state changes in the Alarm.com app. 

I've temporarily disabled the login notifications and texts from Alarm.com, so my phone has stopped blowing up.
I found that when I disable "polling for updates" on the AlarmDotCom Integration, the frequent logins stop but so does my stream of sensor state changes from Alarm.com.

I'm sure I've just configured something incorrectly. 

**How should I configure the AlarmDotCom integration to stay logged into Alarm.com, as to not spam me with login notifications?
While also viewing the Alarm.com sensor states in Home Assistant?**

I don't need to be able to arm and disarm the alarm from HA, but would like to be able to see the sensor states and current panel status. 

Thanks,
Danno

![image](https://user-images.githubusercontent.com/22260702/152206359-333b413f-8f26-4b71-b6ba-b425640287d8.png)

![image](https://user-images.githubusercontent.com/22260702/152206608-ee790f9e-c2cd-40bf-a45f-909064743730.png)

![image](https://user-images.githubusercontent.com/22260702/152206502-0a3c9476-79dd-415e-8ee3-196a91c6e5e8.png)

**Comment by elahd** [comment]
Are you seeing this behavior in both v0.1 and v0.2?

**Comment by DannoPeters** [comment]
I am, I stopped the v0.2 after 10 minutes after getting 7 notifications.

**Comment by elahd** [comment]
Got it. The add-in doesn't keep an open session with the web server -- it logs back in every time it wants to refresh data. It would add decent amount of complexity to (and opportunities to introduce bugs) to keep the connection alive. It would be great it someone could take a stab at implementing a keep-alive model here, but I think the best near-term solution is to turn on 2FA (to beef up security) and to turn off login notifications.

**Comment by DannoPeters** [comment]
Thanks! 2FA did the trick. My provider dint prompt for it so I didn't realize it was available.
