### ISSUE TITLE
Opened/Closed status not supported

### ISSUE THREAD

**Issue by insideoud** [uvjustin/alarmdotcom#85]
when sensor is opened and close quickly there is no entry in HA. if there is a way to detect this behavior for the alarm dot come log  file "Opened/Closed" it would be helpful to register that in HA.

**Comment by elahd** [comment]
This is because the integration polls Alarm.com for updates once per minute. It doesn't get push notifications. Push notifications are only available via the Alarm.com app through an interface that hasn't been reverse engineered.

**Comment by insideoud** [comment]
totally get push notification is not being used as part of this. But can we pull the status from the log and if it behaves like a open/close at least toggle the record in HA so we can see it in history or trigger automation. see a screenshot from alarm dot com:

[](url)
![Picture1](https://user-images.githubusercontent.com/97927319/153069766-b99c7259-19d9-45a5-b011-fb7920a46162.png)
