### ISSUE TITLE
Version 0.2.0 - Smoke / CO sensors?

### ISSUE THREAD

**Issue by mikesalz** [uvjustin/alarmdotcom#87]
Hello!  I LOVE the new update!  Great job!  Previously, I had stupid complicated template sensors using regex_search for CO 1, Smoke 1, CO 2, Smoke 2, etc. in order to derive my CO and smoke sensors.  While I do see my window and door sensors in the updated integration, I am not seeing anything that resembles CO and smoke.  Would they still be included in the update?

**Comment by mikesalz** [comment]
Eh, never mind.  I didn't realize it, but Alarm.com took the liberty of renaming a bunch of my sensors after I originally created the Smoke and CO template sensors.  It named them all "Upstairs" and then complained that I had multiple sensors with the same name.  Nice!  Anyway, I am good now. Thanks again for all of the great work on this integration!

**Comment by elahd** [comment]
Awesome! Glad you sorted this out. Thanks for the feedback.
