### ISSUE TITLE
How to Change Sensor type?

### ISSUE THREAD

**Issue by Raul-7-7** [uvjustin/alarmdotcom#90]
Hi guys, just upgraded to 0.2 and everything seem to work, however, some of the entities are setup wrong, for example, if my window sensor for Bedroom is called "Bedroom" it has created a sensor but with on/off state , however for rooms that my window sensor has th word window in it for example "Basement Window" it has created a correct entity that looks like this
![image](https://user-images.githubusercontent.com/58608128/154823386-40e88bb0-f18f-48fb-a884-390cbc399d14.png)

However for Bedroom window, it looks like this: 
![image](https://user-images.githubusercontent.com/58608128/154823414-4832eea6-204d-41c5-9152-274b0c785ef6.png)

I can not figure out what I need to change to convert Bedroom to a window sensor?
Cheers,

**Comment by elahd** [comment]
Alarm.com doesn't report whether a contact sensor is on a window or a door, so we built some crude logic into the integration that searches for the words "window" and "door" in a bunch of different languages to choose the sensor subtype. If the integration can't find either word, it creates a generic sensor.

You can fix this by either:
1. Adding "window" or "door" to the sensor name in Alarm.com.
2. Use HA's entity customization feature to set a device's class to either window or door. See both https://www.home-assistant.io/docs/configuration/customizing-devices/ and https://www.home-assistant.io/integrations/binary_sensor/.

The list of recognized words/languages for window and door is in https://github.com/uvjustin/alarmdotcom/blob/master/custom_components/alarmdotcom/device_type_langs.py.

**Comment by Raul-7-7** [comment]
Thanks! that worked fine :)
