### ISSUE TITLE
Scan interval

### ISSUE THREAD

**Issue by pdobrien3** [uvjustin/alarmdotcom#99]
Any way we can add a scan interval like earlier versions?  Or possible is there a way to manually edit the scan interval?

**Comment by AritroSaha10** [comment]
Looks like `update_interval` [in line 167 of controller.py](https://github.com/uvjustin/alarmdotcom/blob/master/custom_components/alarmdotcom/controller.py#L167) controls how frequently it's scanned. Maybe this can be changed so that it goes off the configuration entry?

**Comment by elahd** [comment]
This is done in v0.2.3-beta.

**Comment by pdobrien3** [comment]
Thanks.  What is the easiest way to update?  Is it standard practice to delete all the files in custom_components, delete the integration, download the new files and add the integration again?

**Comment by AritroSaha10** [comment]
@pdobrien3 Did you download the integration through HACS? If so, you can update from there

**Comment by pdobrien3** [comment]
No, I don’t use HACS.  I just put the files in the custom_components folder.

**Comment by elahd** [comment]
1. Delete the `custom_components/alarmdotcom` folder.
2. Download the source code zip from https://github.com/uvjustin/alarmdotcom/releases/tag/v0.2.3-beta.
3. Extract the `custom_components/alarmdotcom` folder from the zip file into your `custom_components` folder.
4. Reboot HA.

Your settings will be saved.

I can't recommend HACS enough, though. It makes this entire process 1-click and makes it easier to discover new integrations.
